name: Auto Push Changes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit and Push
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Automated commit" || echo "No changes to commit"
          git push
