name: Autocommit Changes

# Schedule workflow to run at fixed intervals
on:
  # Runs the workflow every hour
  schedule:
    - cron: "*/10 * * * *" # Adjust the cron as needed (e.g., every 5 minutes: "*/5 * * * *")
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure Git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit and push changes if there are any
      - name: Autocommit changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Autocommit: Changes detected"
            git push origin master
          fi
