name: Autocommit Changes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Autocommit changes
        run: |
          # Add all changes, including untracked files
          git add -A
          
          # Check if there are any changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Autocommit: Changes detected"
            git push
          else
            echo "No changes to commit."
          fi
