name: Auto Commit and Push

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (adjust as needed)
  workflow_dispatch: # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Detect Changes and Commit
      run: |
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "Auto-commit: $(date -u)"
        else
          echo "No changes to commit"
        fi

    - name: Push Changes
      run: git push
